/**
 * Runtime message types for The Colony agent loop.
 *
 * 1:1 port of colony/runtime/message.py — represents conversation-level
 * messages flowing through the agent runtime, distinct from the LLM-level
 * wire format sent to providers.
 *
 * Runtime messages carry richer metadata (timestamps, tool call structures,
 * iteration tracking) that the prompt assembler later condenses into
 * LLMMessage instances for the LLM call.
 */

import { randomUUID } from "crypto";

// ---------------------------------------------------------------------------
// ID and timestamp helpers
// ---------------------------------------------------------------------------

function newId(): string {
  return randomUUID().replace(/-/g, "").slice(0, 16);
}

function utcNow(): string {
  return new Date().toISOString();
}

// ---------------------------------------------------------------------------
// Tool-related messages
// ---------------------------------------------------------------------------

/** A structured tool invocation requested by the LLM. */
export interface ToolCall {
  /** Unique identifier for this tool call (correlates with ToolResult). */
  id: string;
  /** Tool / function name to invoke. */
  name: string;
  /** Keyword arguments to pass to the tool. */
  arguments: Record<string, unknown>;
}

export function createToolCall(
  name: string,
  args: Record<string, unknown> = {},
  id?: string,
): ToolCall {
  return { id: id ?? newId(), name, arguments: args };
}

/** Result of executing a tool call. */
export interface ToolResult {
  type: "tool_result";
  /** The ToolCall.id this result corresponds to. */
  toolCallId: string;
  /** Tool name (echoed back for readability). */
  name: string;
  /** String output from the tool. */
  content: string;
  /** True if the tool raised an exception. */
  isError: boolean;
  /** Wall-clock execution time in milliseconds. */
  executionTimeMs: number;
}

export function createToolResult(
  toolCallId: string,
  name: string,
  content: string,
  isError = false,
  executionTimeMs = 0,
): ToolResult {
  return {
    type: "tool_result",
    toolCallId,
    name,
    content,
    isError,
    executionTimeMs,
  };
}

// ---------------------------------------------------------------------------
// Conversation messages
// ---------------------------------------------------------------------------

/** Incoming message from a human or external system. */
export interface UserMessage {
  type: "user";
  id: string;
  content: string;
  timestamp: string;
  metadata: Record<string, unknown>;
}

export function createUserMessage(
  content: string,
  metadata: Record<string, unknown> = {},
): UserMessage {
  return {
    type: "user",
    id: newId(),
    content,
    timestamp: utcNow(),
    metadata,
  };
}

/** Response generated by the LLM, possibly containing tool calls. */
export interface AssistantMessage {
  type: "assistant";
  id: string;
  content: string;
  toolCalls: ToolCall[];
  finishReason: string;
  model: string;
  provider: string;
  tokenUsage: Record<string, number>;
  timestamp: string;
  iteration: number;
}

export function createAssistantMessage(
  content: string,
  opts: Partial<Omit<AssistantMessage, "type" | "id" | "timestamp">> = {},
): AssistantMessage {
  return {
    type: "assistant",
    id: newId(),
    content,
    toolCalls: opts.toolCalls ?? [],
    finishReason: opts.finishReason ?? "",
    model: opts.model ?? "",
    provider: opts.provider ?? "",
    tokenUsage: opts.tokenUsage ?? {},
    timestamp: utcNow(),
    iteration: opts.iteration ?? 0,
  };
}

/** Injected system context (caste identity, instructions, manifesto). */
export interface SystemMessage {
  type: "system";
  id: string;
  content: string;
  /** Higher priority blocks are preserved during context compaction. */
  priority: number;
  timestamp: string;
}

export function createSystemMessage(
  content: string,
  priority = 0,
): SystemMessage {
  return {
    type: "system",
    id: newId(),
    content,
    priority,
    timestamp: utcNow(),
  };
}

// ---------------------------------------------------------------------------
// Union type
// ---------------------------------------------------------------------------

export type RuntimeMessage =
  | UserMessage
  | AssistantMessage
  | SystemMessage
  | ToolResult;

// ---------------------------------------------------------------------------
// Serialized form (stored in session history)
// ---------------------------------------------------------------------------

export interface SerializedMessage {
  type: "user" | "assistant" | "system" | "tool_result";
  content?: string;
  id?: string;
  timestamp?: string;
  metadata?: Record<string, unknown>;
  toolCalls?: Array<Record<string, unknown>>;
  finishReason?: string;
  model?: string;
  provider?: string;
  tokenUsage?: Record<string, number>;
  iteration?: number;
  priority?: number;
  toolCallId?: string;
  name?: string;
  isError?: boolean;
  executionTimeMs?: number;
}

/** Serialize a runtime message to a plain object for session storage. */
export function serializeMessage(msg: RuntimeMessage): SerializedMessage {
  switch (msg.type) {
    case "user":
      return {
        type: "user",
        content: msg.content,
        id: msg.id,
        timestamp: msg.timestamp,
        metadata: msg.metadata,
      };
    case "assistant":
      return {
        type: "assistant",
        content: msg.content,
        id: msg.id,
        toolCalls: msg.toolCalls.map((tc) => ({
          id: tc.id,
          name: tc.name,
          arguments: tc.arguments,
        })),
        finishReason: msg.finishReason,
        model: msg.model,
        provider: msg.provider,
        tokenUsage: msg.tokenUsage,
        timestamp: msg.timestamp,
        iteration: msg.iteration,
      };
    case "system":
      return {
        type: "system",
        content: msg.content,
        id: msg.id,
        priority: msg.priority,
        timestamp: msg.timestamp,
      };
    case "tool_result":
      return {
        type: "tool_result",
        toolCallId: msg.toolCallId,
        name: msg.name,
        content: msg.content,
        isError: msg.isError,
        executionTimeMs: msg.executionTimeMs,
      };
  }
}
