import * as vscode from "vscode";
import { setStoredToken } from "../client-factory";

export function registerSetToken(context: vscode.ExtensionContext): vscode.Disposable {
  return vscode.commands.registerCommand("colony.setToken", async () => {
    const token = await vscode.window.showInputBox({
      title: "Colony: Daemon Bearer Token",
      prompt:
        "Paste the bearer token generated by `colony daemon` (or leave blank to clear it).",
      password: true,
      ignoreFocusOut: true,
    });
    if (token === undefined) return; // cancelled
    await setStoredToken(context, token);
    if (token) {
      vscode.window.showInformationMessage("Colony bearer token saved to SecretStorage.");
    } else {
      vscode.window.showInformationMessage("Colony bearer token cleared.");
    }
  });
}
